sudo: required
services:
    - docker
before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
    - docker build -t rossles/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rossles/react-test npm test